name: Check Formatting
on:
  pull_request:
    branches: 
      - master
jobs:
  format_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Format
        run: |
          cd server
          npm run fmt:c
          cd ../web
          npm run fmt:c
