name: Format
on:
  pull_request:
    branches: [master]
jobs:
  format_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Format Server
        run: |
          npm install -g yarn
          cd web
          yarn install
          yarn fmt:c
      - name: Format Server
        run: |
          cd ../server
          yarn install
          yarn fmt:c
