name: Format Branch
on: workflow_dispatch

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      name: install deps
        run: |
          npm install -g yarn
          cd web
          yarn install
          cd ../server
          yarn install
      - name: Format Web
        run: |
          cd web
          yarn fmt:w
      - name: Format server
        run: |
          cd server
          yarn fmt:w
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
